### ISSUE TITLE
Enhancement: Support comma separated arrays in front matter

### ISSUE THREAD

**Issue by iranzo** [estruyf/vscode-front-matter#102]
**Is your feature request related to a problem? Please describe.**

When using Pelican markdown files with frontmatter I get several issues:

- Tags are added a quote all together, I guess because it expects array type with quoted items, which is not the case with Pelican
- date and modified are quoted... again, not what Pelican expects, causing failures on rendering

**Describe the solution you'd like**

Allow configurable 'frontmatter' styling for 'hugo', 'pelican' or others

**Describe alternatives you've considered**
So far, disabling and uninstalling the extension as it was breaking the articles I've. I've tried setting date format in settings and not add quotes, but still it adds them.

**Comment by iranzo** [comment]
BTW I've found the "frontMatter.taxonomy.noPropertyValueQuotes": ["modified", "date", "tags"], but I think that a dropdown to select compatibility will make it easier ;-)

**Comment by estruyf** [comment]
Thank @iranzo for reporting this. The `frontMatter.taxonomy.noPropertyValueQuotes` setting is exactly meant for this. As some need quotes, and others don't.

Having an optimized settings experience is on backlog #80. The dropdown would be a nice addition to it.

I did some tests, and in the projects, I use for testing it is working as expected, but it might be because of all use `YAML`. 

What is Pelican using? Would you be able to share a sample page with the front matter and content?

**Comment by iranzo** [comment]
Pelican is also using YAML, for example: https://github.com/iranzo/iranzo.github.io/blob/master/content/2021-09-11-rhel8-administration.en.md

**Comment by iranzo** [comment]
I think that there are other things involved in the way Frontmatter processes the files:

![image](https://user-images.githubusercontent.com/312463/133429398-681f615f-ee97-4d97-a76a-d0bd51a050e7.png)


Even if the quotes are not enabled to be used, seems that it tries to read those as 'hugo'-style keys/values

**Comment by estruyf** [comment]
Hugo doesn't use a style, they use YAML format, like other site generators. It is `gray-matter` which does the parsing. 

I'll validate it against your blog content, thanks for the reference.

**Comment by iranzo** [comment]
Sorry, for 'style' I meant for arrays, pelican uses comma separated words, but seems that it expects a `[` and `]` for specifying more than one tag

**Comment by estruyf** [comment]
There are two issues:

1. The title contains `[]` - so the YAML parser thinks you're adding an array
2. Arrays in YAML can be `[]` or like:

```
tags:
  - tag 1
  - tag 2
```

**Comment by iranzo** [comment]
Yes, and 'neither' example 1, or example 2 are taken by pelican (I guess it should), but only parses keywords as comma-separated words

**Comment by estruyf** [comment]
The title will need to be manually escaped. I will add a title input on the panel as well soon so that it will automatically escape it for you. 

![Screenshot 2021-09-15 at 14 56 46](https://user-images.githubusercontent.com/2900833/133437845-fd9d75c9-6d6e-41d6-b98e-774e145ac61d.png)


![Screenshot 2021-09-15 at 14 57 10](https://user-images.githubusercontent.com/2900833/133437875-bc8b07c4-790c-476d-9330-12b5cd361250.png)

**Comment by estruyf** [comment]
I got good news, I changed some internal logic and the new version will be able to work with comma-separated array values.

In order to support this, you'll have to do the following in your `settings.json`:

```
{
  "frontMatter.taxonomy.commaSeparatedFields": [
    "tags"
  ],
  "frontMatter.taxonomy.noPropertyValueQuotes": [
    "tags"
  ],
  "frontMatter.taxonomy.tags": [
    "Packt Publishing",
    "RHCSA",
    "RHEL",
    "book",
    "system administration",
    "foss"
  ]
}
```

As the comma-separated arrays are not valid YAML, you will have to let Front Matter know how to parse it. That is why the new `frontMatter.taxonomy.commaSeparatedFields` is introduced.

If you want to test it out, you can install the beta version of Front Matter: https://beta.frontmatter.codes - https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-front-matter-beta 

Be sure to uninstall the main version, as the two cannot run or be installed at the same time.
