### ISSUE TITLE
Enhancement: let users sort their files in media dashboard

### ISSUE THREAD

**Issue by LuiseFreese** [estruyf/vscode-front-matter#178]
**Is your feature request related to a problem? Please describe.**
I don't want to go over several pages of media in order to find the image I want to insert. 

**Describe the solution you'd like**
let me (and other users) sort their files, from A-Z, new to old and/or implement search to search for a specific image

**Describe alternatives you've considered**
alternative is to manually insert the link and not previewing the image in the dashboard

**Additional context**
-

**Comment by estruyf** [comment]
Thanks @LuiseFreese! It makes a lot of sense to have this functionality added to the media dashboard!

**Comment by estruyf** [comment]
@LuiseFreese first implementation of the sorting for the media dashboard is completed. At the moment, only sorting based on the filename is supported.

Sorting by the creation/modified date is a bit tricky, as that can lead to performance issues depending on the number of files. Currently, the dashboard shows batches of 16 files, if we want to enable this type of sorting. The statistics of all files need to be fetched first before sorting can be accomplished.

**Comment by estruyf** [comment]
Feel free to test out the latest beta which has the filename sorting in place.

**Comment by estruyf** [comment]
@zivbk1 I have been thinking about that as well. Although I'm not a fan of syncing. Most of the time, it causes issues but thinking about a better and more robust solution. 

Question to @LuiseFreese and @zivbk1. What do your asset folders look like? Is it one folder with all the files? Or multiple folders to structure the content?

If it is the last, it might less be an issue, as fewer files will be retrieved all at once than if you have all files in the root folder.

**Comment by zivbk1** [comment]
I typically have a single 'uploads' folder under my 'static' folder in Hugo where I put all the images that are used in content and layouts.  I don't tend to put any subfolders inside of it.
I do have some sites where all of my media assets (images, videos, binary files (PDF, ZIP, XLSX, etc.)) are in different folders, but the images folder doesn't have any subdirectories.  These assets are not stored in my git repo.  I put them in an S3 bucket and use CloudFront to expose the bucket to the world at a custom subdomain, like files.mydomain.com.  The only downside to this is most editors can't just insert a path reference.  In this case, I only ask the editors to use the asset filename in the content source or frontmatter parameter and I use shortcodes, partials, render hooks, etc. to use the correct URL to the asset when it is rendered to the browser.  Having an integration to upload and list files in an S3 bucket would be awesome in the FM UI, because I could do this same trick with all my sites and get binaries out of my repo as much as possible.

**Comment by estruyf** [comment]
Those are good insights @zivbk1! For the media snippet, would it help for you that there is also a `{filename}` token besides the: mediaUrl, caption, and alt?

**Comment by zivbk1** [comment]
Yes, that would help with the DAM use case, where the files live outside of the repo.

**Comment by LuiseFreese** [comment]
I have an `images` folder in my `static` folder for my Hugo site.. no subfolders :-)

**Comment by estruyf** [comment]
New beta version with support for macOS and Linux date sorting. The next step is to work on support for Windows.

**Comment by LuiseFreese** [comment]
So it could already work on WSL2?

**Comment by estruyf** [comment]
Hasn't been tested in WSL, but it could work. As WSL2 is "just" Linux.

**Comment by estruyf** [comment]
Windows support has been added as well. @LuiseFreese @zivbk1 could you verify this on the beta that it's working for you? I've tested it on my devices, but that is not always a good reference 😊

**Comment by zivbk1** [comment]
I use GitPod, which I think uses a version of Ubuntu Linux.

**Comment by estruyf** [comment]
@zivbk1 true! I've just tested it on a GitHub Codespace, there it seems to work too.

**Comment by estruyf** [comment]
Ok, I went back to the original file checks. As its performance is way better. 🙃

At least it was a good validation.

**Comment by LuiseFreese** [comment]
I can confirm it works on Windows 10 and in WSL2 🚀🚀

**Comment by estruyf** [comment]
Thanks, @LuiseFreese for confirming this!

**Comment by zivbk1** [comment]
It works well in GitPod too! :D

**Comment by estruyf** [comment]
Thanks @zivbk1!

**Comment by zivbk1** [comment]
@estruyf can we define the sort options like we can with our content types?

**Comment by estruyf** [comment]
Not at the moment, but it could be a new option/property to be added.

**Comment by estruyf** [comment]
BTW @zivbk1 on what things do you want to sort your media?

**Comment by zivbk1** [comment]
@estruyf Off the top of my head would be:
- filename
- size
- date
- title
- alt text

The last two above would need to come from the media DB file if defined.

If there is a way to query/store the following data I could see them as useful also.

-width (px)
-height (px)

**Comment by estruyf** [comment]
Now available in the `v5.6.0` release
