### ISSUE TITLE
Issue: Placeholders not working when used in choice fields

### ISSUE THREAD

**Issue by wemasoe** [estruyf/vscode-front-matter#236]
The slug is not beeing optimized when type is choice.

```
        {
          "title": "Permalink1",
          "name": "permalink1",
          "type": "choice",
          "choices": [
            "{{permalink}}",
            "{{title}}",
            "{{slug}}"
          ]
        },
```

output:
![image](https://user-images.githubusercontent.com/97720470/150668176-789716be-f44d-4903-bb50-fbb86e82e059.png)

**Comment by estruyf** [comment]
This is by design, as this would conflict with the selected choice field its value. When we would update the `permalink1` its value from the placeholder to the actual title, slug, ... value, its original value would not be selected anymore.

These placeholders are meant for content creation. If there is anything to happen once the content has already been created, this will need to be achieved by the defined actions or defining your own. Did you know you could create your own custom actions to process your content? More information at: https://frontmatter.codes/docs/custom-actions

**Comment by wemasoe** [comment]
@estruyf Thank you for the detailed answer.
