### ISSUE TITLE
Enhancement: Make page title in lists configurable (title from front matter instead of folder/file name)

### ISSUE THREAD

**Issue by davidsneighbour** [estruyf/vscode-front-matter#322]
**Is your feature request related to a problem? Please describe.**
This might be specific to GoHugo. On content lists in the side panel of the dashboard, I can see lists of "recently modified" pages. The list for the blog section (which is created from page bundles) looks relatively ok (using the folder name of each page bundle which is the title with dashes), the one for tags has `_index.md` as title.

[Sample content structure in my website repo](https://github.com/davidsneighbour/kollitsch.de/tree/main/content)

**Describe the solution you'd like**
 It might be useful if there would be a configuration option to tell Front Matter how to retrieve the title for lists. In most cases that might be the `title` frontmatter as opposed to file/folder names. 

I can think of three values:
- title of the file
- title of the folder
- title front matter value of markdown file in page bundle

I think it might be complicated to do when a page bundle has multiple markdown files. On the other side, the lists on the dashboard itself all have valid titles (even for the tags), so internally that information is somehow parsed/prepared.

**Describe alternatives you've considered**
There is no alternative in regards to GoHugo, as the tags-folder is an internal taxonomy and it can't be switched between single files or page bundles. It has to be `tags/tagname/_index.md` to work properly.

**Additional context**
![20220412-19:44:55-Selection-001](https://user-images.githubusercontent.com/83281/162966537-11cbce9f-aa49-4601-a5f8-ffe0733ec71c.png)

**Comment by estruyf** [comment]
By default, the recently modified section will show the file name. If the file name is `index.md`, it will show the folder name instead. The reason why the current file or folder name is used, is for performance reasons, as otherwise an additional file read is required. 

These `_index.md` index pages typically do not get changed, so will only appear in the list when you update them. We could include an additional read for these index pages, but not sure if this would be beneficial. 

Question: Are you going to put additional content in your `tags` folder? Or is this only going to be used for the roll-up of your tags/taxonomy?

**Comment by estruyf** [comment]
Will be testable in the latest beta
