### ISSUE TITLE
Issue: When using a High Contrast theme, FrontMatter only displays in light mode

### ISSUE THREAD

**Issue by corbob** [estruyf/vscode-front-matter#485]
**Describe the bug**
VSCode by default ships with a number of high contrast themes. Some of these are dark, and some are light. FrontMatter only displays in light mode regardless of which high contrast theme you select.

**To Reproduce**
1. Open FrontMatter Dashboard
2. Ctrl (Cmd) + Shift + P
3. Search for "Preferences: Color Theme"
4. Cycle through the themes available including high contrast themes.

**Expected behavior**
I would expect when using a dark high contrast theme, for the FrontMatter Dashboard to also use a dark theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/30301021/208548700-eab3a29a-a7dd-4a6c-8b14-e795c2799c7a.png)

**Desktop (please complete the following information):**
 - OS: macOS Ventura
 - Browser: VS Code?
 - Version: 1.74.1

**Smartphone (please complete the following information):**
NA

**Additional context**
NA

**Comment by estruyf** [comment]
@corbob thanks for opening this issue. Instead of creating a new high contrast version for Front Matter, I started to implement VSCode theme support. This is currently available in the latest beta version.

In case you would like to give it a try, you can do so by installing the beta version and add the following setting in your `frontmatter.json` file.

```json
{
	"frontMatter.experimental": true,
}
```
