### ISSUE TITLE
Support TOML

### ISSUE THREAD

**Issue by TjeuKayim** [estruyf/vscode-front-matter#6]
Some static site generators support the TOML language instead of YAML, like Hugo.
[Zola](https://github.com/getzola/zola/) only allows TOML as front-matter language.

Would it be hard to implement other front-matter languages?

**Comment by estruyf** [comment]
@TjeuKayim I have to look into it, but I could introduce an option to specify your markup preference. Like YAML as default, and TOML when you specify it.

**Comment by StefanoCecere** [comment]
i want to add that Hugo fully sopports YAML aside TOML (and JSON)
and that many core developers are starting to prefer YAML since it's much more used by .md editors. since there aren't any different features, they're just "formats" of the same content, i agree in having YAML as default and an option to switch to TOML

**Comment by estruyf** [comment]
This functionality has now been added to the extension. Feel free to test it out and provide feedback.
