### ISSUE TITLE
Issue: When using nuxt-content, the preview page does not update in real time.

### ISSUE THREAD

**Issue by Ahidada** [estruyf/vscode-front-matter#667]
**Describe the bug**
When using nuxt-content, the preview page does not update in real time. You need to mouse over the preview window to refresh it. But it can be refreshed in real time in the browser.

**To Reproduce**
1. Go to 'init nuxt content template & open a markdown file'
2. Click on ' Open preview'

**Expected behavior**
Expect the preview window to refresh in real time

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac

**Comment by estruyf** [comment]
Thank you for opening this issue @Ahidada, I have done some testing, and it seems to be an issue with the DEV server of Nuxt when showing the content in an iframe. Right now I don't have an idea yet how to fix it. I opened a Nuxt discussion to get help on this: https://github.com/nuxt/nuxt/discussions/23264

**Comment by estruyf** [comment]
In Discord, yeing mentioned that the Microsoft Edge Tools for VS Code allow a better web preview. I have been looking into it, and it is because under the hood they make use of Puppeteer to screencast the browser view.

The extension itself is intended to be used for development and comes with a lot more features. Alternatively, I found the [Browse Lite](https://marketplace.visualstudio.com/items?itemName=antfu.browse-lite) extension allowing Front Matter to open a given URL.

To fix this, Front Matter will add support for this extension. If it is installed, it will use that to show the preview instead of the built-in preview. This change will solve the issue you are facing with Nuxt.

https://github.com/estruyf/vscode-front-matter/assets/2900833/d1ced1ca-837f-497d-951d-e34839331856

**Comment by estruyf** [comment]
This is testable in the latest beta version

**Comment by Ahidada** [comment]
Thanks. This is great.
